[tool.black]
line-length = 100
target-version = ["py311"]
[tool.ruff]
line-length = 100
target-version = "py311"
select = ["E","F","I","UP","B","SIM","C90","N","ANN","S","BLE","A","COM","TID","DTZ"]
ignore = ["ANN101","ANN102"]
[tool.ruff.isort]
known-first-party = ["app"]
combine-as-imports = true
[tool.mypy]
python_version = "3.11"
warn_unused_ignores = true
warn_redundant_casts = true
disallow_untyped_defs = true
no_implicit_optional = true
strict_equality = true
exclude = ["tests/"]
