name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt -r api/dev-requirements.txt

      - name: Ruff (lint)
        run: ruff check api

      - name: Black (format check)
        run: black --check api

      - name: Mypy (type check)
        run: mypy api

      - name: Pytest
        run: pytest -q
